### PR TITLE
fix: Test for PR PipelineActivity being populated by build controller

### PR DESCRIPTION
**Pull request by abayer**
Testing for non-boot scenarios with https://github.com/jenkins-x/jx/pull/6731

fixes https://github.com/jenkins-x/jx/issues/6738

### CODE REVIEW

**Comment by garethjevans** [comment]
@abayer I like that you are not using some of the JX internals for this, validating via kubectl is a much better way

**Comment by abayer** [comment]
Keeping in WIP until https://github.com/jenkins-x/jx/pull/6731 passes just to be safe.

**Comment by abayer** [comment]
@garethjevans I _almost_ did something like we do at https://github.com/jenkins-x/bdd-jx/blob/eecf572744ac9833305a17f7035c002a524e2e35/test/helpers/test.go#L258-L259, marshaling the output to a `PipelineActivity`, but decided we only needed the one field so why even bother, since this way we get to avoid any possible issues with marshaling due to changes in the struct, but yeah, never even considered anything but `kubectl`.

**Comment by abayer** [comment]
dangit, test still passed when it shouldn't have.

**Comment by abayer** [comment]
Yaaaaay this finally fails when it's supposed to fail and passes when it's supposed to pass. =) Removing WIP for good.

**Comment by dgozalo** [comment]
Looking good, hopefully this is the first set of tests that actually check the status of a `PipelineActivity`, as we are using it quite a lot in the UI.

**Comment by abayer** [comment]
Just overrode because it actually had passed, but something went screwy in reporting it.

**Pull request merged**
