### PR TITLE
feat: Moved default app command tests to leverage test app

### PR DESCRIPTION
**Pull request by deanesmith**
… jacoco app

### CODE REVIEW

**Comment by pmuir** [comment]
@deanesmith do we still need this? Can you resolve the conflicts?

**Comment by deanesmith** [comment]
> @deanesmith do we still need this? Can you resolve the conflicts?

@pmuir yes, I think so.  For the sole purpose of app command end-to-end testing.

**Comment by hferentschik** [comment]
@deanesmith is this still something you want to merge? If so it would need a rebase. Otherwise, I am going to close this pull request.

**Comment by hferentschik** [comment]
@deanesmith I am going to close this PR. If you get around rebasing it, just open a new PR.

**Pull request closed without merging**
