### PR TITLE
BDD Tests for `import --url`

### PR DESCRIPTION
**Pull request by agentgonzo**
Depends on #9 

It's not clear to me whether the two `Context`s defined in the test will run in parallel or series. We would want them to run in parallel. To me it makes it easier to read if these two tests are in the same file, but if they need to be in different files to run in parallel then please let me know and I'll change it.

### CODE REVIEW

**Comment by agentgonzo** [comment]
@ccojocar - there's no prow config for this (That's been added  as https://github.com/jenkins-x/prow-config/pull/168) so /test this won't work until that's been merged.

**Comment by agentgonzo** [comment]
It also needs the jenkinsfile - see https://github.com/jenkins-x/bdd-jx/pull/16

**Comment by mikecirioli** [comment]
@garethjevans / @pmuir / @jstrachan  - can you review/merge this please?

**Pull request closed without merging**
