### PR TITLE
feat: adding tests for Jenkins X UI

### PR DESCRIPTION
**Pull request by hferentschik**
See https://github.com/cloudbees/cloudbees-jenkins-x-distro/issues/49

### CODE REVIEW

**Comment by hferentschik** [comment]
Current PR works on a cluster where the initial boot config changes are merged. It will fail within `jx` since the created cluster does not merge the updated boot config (yet).

**Comment by abayer** [comment]
/lgtm

Woo!

**Comment by abayer** [comment]
Oh right, this repo lies about tide. I'll just merge.

**Comment by hferentschik** [comment]
Sweet, thanks.

**Pull request merged**
