### PR TITLE
fix: so that BDD tests actually run rather than just do a build ;)

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by abayer** [comment]
Ok, so this is a bit hairy - it means that a release build will run `make bdd` against the prod cluster, which isn’t exactly right.

**Comment by rawlingsj** [comment]
Do we have a release pipeline for this?  I'm basically undoing https://github.com/jenkins-x/bdd-jx/commit/b3fa2a5699d19b86aaf64056322da0ca76444b70 as that disabled actually running any tests since it was committed.  ATM we don't know what PRs have merged and not had any bdd tests run?  So wonder if it's best to keep this and remove the release pipeline on the prod cluster if one is there?  Do you happen to know if one was added as part of this change or has there always been one and you saw this and realised the issue you mention?

**Comment by abayer** [comment]
Yeah, we do have a release pipeline now. And yeah, removing the release pipeline on prod probably does make sense.

**Comment by abayer** [comment]
...and that release pipeline went and created https://github.com/jenkins-x/environment-tekton-weasel-dev/pull/270. =)

**Comment by rawlingsj** [comment]
wow - ok great catch, I didn't know we'd added a release pipeline, cool I'll find it and disable it.

**Pull request merged**
